#!/bin/bash
version="bun-v1.3.13"
scriptDir="$(cd "$(dirname "$0")" && pwd)"
platform="$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)"
downloadDir="$scriptDir/download/bun/${version}/${platform}"
bunCmd="$downloadDir/bin/bun"
if [ ! -f "$bunCmd" ]; then
    echo Installing bun to "$bunCmd"
    bashArgs=()
    if [ "$version" != "latest" ]; then
        bashArgs=(-s "$version")
    fi
    curl -fsSL https://bun.sh/install | BUN_INSTALL="$downloadDir" bash "${bashArgs[@]}"
fi
exec "$bunCmd" "$@"
