import type { SQL } from "bun";

// =============================================================================
// Errors
// =============================================================================

/**
 * Thrown when a feature is not yet implemented
 */
export class NotImplementedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "NotImplementedError";
  }
}

// =============================================================================
// Context
// =============================================================================

/**
 * Context passed to all ops functions
 */
export interface OpsContext {
  /** Database connection or transaction handle */
  sql: SQL;
  /** Schema name (e.g., "me_abc123xyz789") */
  schema: string;
  /** Shard number for pgDog routing (optional, future use) */
  shard?: number;
  /** Whether we're inside a transaction (controls whether withTx opens a new one) */
  inTransaction: boolean;
  /** Get the current user ID (for RLS context) */
  getUserId: () => string | null;
}

// =============================================================================
// User
// =============================================================================

/**
 * User: thing that accesses memories within an engine.
 * Can be linked to an identity (soft FK to accounts.identity) or standalone.
 * If can_login = false, it's a role (grant container for RBAC).
 */
export interface User {
  id: string;
  name: string;
  identityId: string | null;
  canLogin: boolean;
  superuser: boolean;
  createrole: boolean;
  createdAt: Date;
  updatedAt: Date | null;
}

export interface CreateUserParams {
  id?: string;
  name: string;
  identityId?: string | null;
  canLogin?: boolean;
  superuser?: boolean;
  createrole?: boolean;
}

// =============================================================================
// API Key
// =============================================================================

/**
 * API key for authenticating to an engine.
 * Scoped to a user within this engine.
 */
export interface ApiKey {
  id: string;
  userId: string;
  lookupId: string;
  name: string;
  expiresAt: Date | null;
  lastUsedAt: Date | null;
  createdAt: Date;
  revokedAt: Date | null;
}

export interface CreateApiKeyParams {
  userId: string;
  name: string;
  expiresAt?: Date | null;
}

export interface CreateApiKeyResult {
  apiKey: ApiKey;
  /** The full API key string (only returned on creation) */
  rawKey: string;
}

export interface ValidateApiKeyResult {
  valid: boolean;
  userId?: string;
  apiKeyId?: string;
  error?: string;
}

// =============================================================================
// Tree Grant
// =============================================================================

export interface TreeGrant {
  id: string;
  userId: string;
  treePath: string;
  actions: string[];
  grantedBy: string | null;
  withGrantOption: boolean;
  createdAt: Date;
}

export interface GrantTreeAccessParams {
  userId: string;
  treePath: string;
  actions: string[];
  grantedBy?: string | null;
  withGrantOption?: boolean;
}

// =============================================================================
// Tree Owner
// =============================================================================

export interface TreeOwner {
  treePath: string;
  userId: string;
  createdBy: string | null;
  createdAt: Date;
}

// =============================================================================
// Role
// =============================================================================

export interface RoleMember {
  roleId: string;
  memberId: string;
  withAdminOption: boolean;
  createdAt: Date;
}

export interface RoleInfo {
  id: string;
  name: string;
  withAdminOption: boolean;
}

// =============================================================================
// Memory
// =============================================================================

export interface Memory {
  id: string;
  content: string;
  meta: Record<string, unknown>;
  tree: string;
  temporal: { start: Date; end: Date } | null;
  hasEmbedding: boolean;
  createdAt: Date;
  createdBy: string | null;
  updatedAt: Date | null;
}

export interface CreateMemoryParams {
  id?: string;
  content: string;
  meta?: Record<string, unknown>;
  tree?: string;
  temporal?: { start: Date; end?: Date } | null;
  createdBy?: string | null;
}

export interface UpdateMemoryParams {
  content?: string;
  meta?: Record<string, unknown>;
  tree?: string;
  temporal?: { start: Date; end?: Date } | null;
}

// =============================================================================
// Search
// =============================================================================

export interface SearchParams {
  /** Semantic search query (text - embedding must be generated by caller) */
  semantic?: string;
  /** Pre-computed embedding vector for semantic search */
  embedding?: number[];
  /** Full-text (BM25) search query */
  fulltext?: string;
  /** Regex filter applied to content (POSIX, case-sensitive) */
  grep?: string;
  /** Filter by tree path (ltree, lquery, or ltxtquery) */
  tree?: string;
  /** Filter by metadata (JSONB containment) */
  meta?: Record<string, unknown>;
  /** Temporal filter */
  temporal?: TemporalFilter;
  /** Maximum results (default: 10) */
  limit?: number;
  /** Candidates per search mode before RRF fusion */
  candidateLimit?: number;
  /** Weights for hybrid search */
  weights?: SearchWeights;
  /** Sort direction for filter-only searches */
  orderBy?: "asc" | "desc";
}

export interface TemporalFilter {
  /** Find memories containing this point in time */
  contains?: Date | string;
  /** Find memories overlapping this range [start, end] */
  overlaps?: [Date | string, Date | string];
  /** Find memories fully within this range [start, end] */
  within?: [Date | string, Date | string];
}

export interface SearchWeights {
  semantic?: number;
  fulltext?: number;
}

export interface SearchResult {
  results: SearchResultItem[];
  total: number;
  limit: number;
}

export interface SearchResultItem extends Memory {
  score: number;
}

// =============================================================================
// Tree
// =============================================================================

export interface GetTreeParams {
  /** Root path to start from (default: root) */
  tree?: string;
  /** Maximum depth to return */
  levels?: number;
}

export interface TreeNode {
  path: string;
  count: number;
}
