#!/usr/bin/env bun
/**
 * Bundle `packages/web/dist/` into a TypeScript module that the CLI can
 * import. Produces `packages/cli/serve/web-assets.generated.ts` which
 * exports a `Map<path, { contentType, data }>`.
 *
 * Run after `vite build` and before `bun build --compile` so the UI ships
 * inside the `me` binary. Safe to run with no dist/: emits an empty map.
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, sep } from "node:path";

const REPO_ROOT = join(import.meta.dir, "..");
const WEB_DIST = join(REPO_ROOT, "packages/web/dist");
const OUT_PATH = join(REPO_ROOT, "packages/cli/serve/web-assets.generated.ts");

const EXT_TO_MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".txt": "text/plain; charset=utf-8",
};

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      out.push(...walk(full));
    } else if (stat.isFile()) {
      out.push(full);
    }
  }
  return out;
}

function contentTypeFor(path: string): string {
  const dot = path.lastIndexOf(".");
  if (dot === -1) return "application/octet-stream";
  const ext = path.slice(dot).toLowerCase();
  return EXT_TO_MIME[ext] ?? "application/octet-stream";
}

interface AssetEntry {
  path: string;
  contentType: string;
  base64: string;
}

function collectAssets(): AssetEntry[] {
  if (!existsSync(WEB_DIST)) return [];

  const files = walk(WEB_DIST);
  const entries: AssetEntry[] = [];
  for (const file of files) {
    const rel = relative(WEB_DIST, file).split(sep).join("/");
    // Skip sourcemaps — they roughly double the embedded size and aren't
    // needed at runtime. Set ME_EMBED_SOURCEMAPS=1 to include them.
    if (rel.endsWith(".map") && !process.env.ME_EMBED_SOURCEMAPS) continue;
    const urlPath = `/${rel}`;
    const bytes = readFileSync(file);
    entries.push({
      path: urlPath,
      contentType: contentTypeFor(rel),
      base64: bytes.toString("base64"),
    });
  }
  // Stable output order for reproducible builds.
  entries.sort((a, b) => a.path.localeCompare(b.path));
  return entries;
}

function renderModule(entries: AssetEntry[]): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/bundle-web-assets.ts. Do not edit.");
  lines.push("// Regenerate with `./bun scripts/bundle-web-assets.ts`.");
  lines.push("");
  lines.push("export interface EmbeddedAsset {");
  lines.push("  contentType: string;");
  lines.push("  data: Uint8Array;");
  lines.push("}");
  lines.push("");
  lines.push("function decode(b64: string): Uint8Array {");
  lines.push('  return Uint8Array.from(Buffer.from(b64, "base64"));');
  lines.push("}");
  lines.push("");
  lines.push(
    "export const webAssets: ReadonlyMap<string, EmbeddedAsset> = new Map([",
  );
  for (const e of entries) {
    const pathLit = JSON.stringify(e.path);
    const ctLit = JSON.stringify(e.contentType);
    const b64Lit = JSON.stringify(e.base64);
    lines.push(
      `  [${pathLit}, { contentType: ${ctLit}, data: decode(${b64Lit}) }],`,
    );
  }
  lines.push("]);");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const entries = collectAssets();
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, renderModule(entries));
  const total = entries.reduce((n, e) => n + e.base64.length, 0);
  console.log(
    `[bundle-web-assets] wrote ${entries.length} assets (${Math.round(
      total / 1024,
    )} KB base64) -> ${relative(REPO_ROOT, OUT_PATH)}`,
  );
  if (entries.length === 0) {
    console.log(
      "[bundle-web-assets] note: packages/web/dist/ is empty. Run `cd packages/web && ../../bun run build` first to embed the UI.",
    );
  }
}

main();
