// Integration test for the memory RPC data-plane handlers (4C-1).
//
// Provisions a space + owner, then drives the memory.* handlers through the
// registry against a real space schema (me_<slug>). Semantic search is not
// exercised (embeddings are generated by the worker — Phase 4D); fulltext
// (bm25) and filter search are.
//   TEST_DATABASE_URL="postgresql://postgres@127.0.0.1:5432/postgres" \
//     bun test --timeout 30000 \
//     packages/server/rpc/memory/memory.integration.test.ts
import { afterAll, beforeAll, beforeEach, expect, test } from "bun:test";
import { bootstrapSpaceDatabase, migrateCore } from "@memory.build/database";
import type { TreeAccess } from "@memory.build/engine/core";
import * as engineCore from "@memory.build/engine/core";
import type { SpaceStore } from "@memory.build/engine/space";
import * as engineSpace from "@memory.build/engine/space";
import { type AppErrorCode, isAppError } from "@memory.build/protocol/errors";
import postgres, { type Sql } from "postgres";
import { seedUserSpace } from "../../test-support";
import type { HandlerContext } from "../types";
import { memoryDataMethods } from "./memory";

const URL =
  process.env.TEST_DATABASE_URL ??
  "postgresql://postgres@127.0.0.1:5432/postgres";

const rand = () => {
  const a = "abcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = crypto.getRandomValues(new Uint8Array(8));
  let s = "";
  for (const b of bytes) s += a[b % 36];
  return s;
};

let sql: Sql;
let coreSchema: string;
const createdSpaceSchemas: string[] = [];

// Per-test space context.
let store: SpaceStore;
let treeAccess: TreeAccess;
let space: { id: string; slug: string };
let principalId: string;

function call<T = unknown>(
  method: string,
  params: unknown,
  ta: TreeAccess = treeAccess,
): Promise<T> {
  const registered = memoryDataMethods.get(method);
  if (!registered) throw new Error(`no handler for ${method}`);
  const context = {
    request: new Request("http://localhost/api/v1/memory/rpc"),
    store,
    core: engineCore.coreStore(sql, coreSchema),
    space,
    principalId,
    ownerId: null, // user/session caller
    apiKeyId: null,
    treeAccess: ta,
  } as unknown as HandlerContext;
  return registered.handler(params, context) as Promise<T>;
}

/** Assert a handler call rejects with a specific AppError code. */
async function expectAppError(p: Promise<unknown>, code: AppErrorCode) {
  try {
    await p;
    throw new Error(`expected AppError(${code}), but it resolved`);
  } catch (e) {
    if (!isAppError(e)) throw e;
    expect(e.code).toBe(code);
  }
}

beforeAll(async () => {
  sql = postgres(URL, { onnotice: () => {} });
  coreSchema = `core_test_${rand()}`;
  await bootstrapSpaceDatabase(sql);
  await migrateCore(sql, { schema: coreSchema });
});

afterAll(async () => {
  for (const s of createdSpaceSchemas) {
    await sql.unsafe(`drop schema if exists ${s} cascade`);
  }
  await sql.unsafe(`drop schema if exists ${coreSchema} cascade`);
  await sql.end();
});

// Fresh space per test so trees don't bleed across cases.
beforeEach(async () => {
  const core = engineCore.coreStore(sql, coreSchema);
  const r = await seedUserSpace(
    sql,
    { core: coreSchema },
    {
      email: `mem_${crypto.randomUUID().slice(0, 8)}@example.com`,
      name: "Owner",
    },
  );
  createdSpaceSchemas.push(`me_${r.spaceSlug}`);
  store = engineSpace.spaceStore(sql, `me_${r.spaceSlug}`);
  // The default creator owns its home + the shared root (`share`), not the whole
  // tree — so these tests write under `share.*`. (The normalization test, which
  // needs arbitrary paths, elevates itself to owner@root.)
  treeAccess = await core.buildTreeAccess(r.userId, r.spaceId);
  space = { id: r.spaceId, slug: r.spaceSlug };
  principalId = r.userId;
});

test("~ home + lenient separators normalize on input, reverse-map on output", async () => {
  // This test writes to arbitrary (non-home, non-share) paths to exercise path
  // normalization, so elevate the owner to owner@root for it.
  const core = engineCore.coreStore(sql, coreSchema);
  await core.grantTreeAccess(
    space.id,
    principalId,
    engineCore.ROOT_PATH,
    engineCore.ACCESS.owner,
  );
  treeAccess = await core.buildTreeAccess(principalId, space.id);

  const home = `home.${principalId.replace(/-/g, "")}`;

  // `~/notes` (slash accepted on input) stores under the caller's home and
  // reads back in canonical slash form as `~/notes`.
  const a = await call<{ id: string; tree: string }>("memory.create", {
    content: "home note",
    tree: "~/notes",
  });
  expect(a.tree).toBe("~/notes");
  expect((await call<{ tree: string }>("memory.get", { id: a.id })).tree).toBe(
    "~/notes",
  );

  // The raw stored ltree is home.<id>.notes — proves real expansion, not just display.
  const [row] = await sql.unsafe(
    `select tree::text as tree from me_${space.slug}.memory where id = $1`,
    [a.id],
  );
  expect(row?.tree).toBe(`${home}.notes`);

  // Slash input normalizes to dot ltree; non-home paths display canonically.
  const b = await call<{ tree: string }>("memory.create", {
    content: "slashy",
    tree: "/work/projects/",
  });
  expect(b.tree).toBe("/work/projects");

  // memory.tree with a `~` base finds the home node, reverse-mapped to `~/notes`.
  const tree = await call<{ nodes: { path: string; count: number }[] }>(
    "memory.tree",
    { tree: "~" },
  );
  expect(tree.nodes.some((n) => n.path === "~/notes")).toBe(true);

  // An illegal label is a validation error.
  await expectAppError(
    call("memory.create", { content: "x", tree: "bad label" }),
    "VALIDATION_ERROR",
  );
});

test("create without a tree is a validation error (tree is required)", async () => {
  // `tree` is required on the wire — callers must choose `share` vs `~`
  // explicitly. The file importers default to `share`, but a bare RPC create
  // does not.
  await expectAppError(
    call("memory.create", { content: "no tree given" }),
    "VALIDATION_ERROR",
  );
});

test("create → get round-trips content/tree/meta and createdBy is null", async () => {
  const created = await call<{ id: string; createdBy: string | null }>(
    "memory.create",
    { content: "hello world", tree: "share.notes.work", meta: { tag: "a" } },
  );
  expect(created.createdBy).toBeNull();

  const got = await call<{
    id: string;
    content: string;
    tree: string;
    meta: Record<string, unknown>;
    hasEmbedding: boolean;
  }>("memory.get", { id: created.id });
  expect(got.content).toBe("hello world");
  expect(got.tree).toBe("/share/notes/work");
  expect(got.meta).toEqual({ tag: "a" });
  expect(got.hasEmbedding).toBe(false);
});

test("create with temporal round-trips as {start,end}", async () => {
  const created = await call<{ id: string }>("memory.create", {
    content: "temporal one",
    tree: "share",
    temporal: { start: "2024-01-01T00:00:00Z", end: "2024-01-02T00:00:00Z" },
  });
  const got = await call<{ temporal: { start: string; end: string } | null }>(
    "memory.get",
    { id: created.id },
  );
  expect(got.temporal).toEqual({
    start: "2024-01-01T00:00:00.000Z",
    end: "2024-01-02T00:00:00.000Z",
  });
});

test("name: getByPath / deleteByPath address a named memory; response carries name", async () => {
  const created = await call<{ id: string; name: string | null }>(
    "memory.create",
    { content: "rotation notes", tree: "share/auth", name: "jwt-rotation" },
  );
  expect(created.name).toBe("jwt-rotation");

  // getByPath splits the final segment as the name and resolves it.
  const got = await call<{ id: string; tree: string; name: string | null }>(
    "memory.getByPath",
    { path: "share/auth/jwt-rotation" },
  );
  expect(got.id).toBe(created.id);
  expect(got.tree).toBe("/share/auth");
  expect(got.name).toBe("jwt-rotation");

  // a path that doesn't resolve is NOT_FOUND
  await expectAppError(
    call("memory.getByPath", { path: "share/auth/missing" }),
    "NOT_FOUND",
  );

  const del = await call<{ deleted: boolean }>("memory.deleteByPath", {
    path: "share/auth/jwt-rotation",
  });
  expect(del.deleted).toBe(true);
  await expectAppError(call("memory.get", { id: created.id }), "NOT_FOUND");
});

test("name: create onConflict error (default) / ignore / replace", async () => {
  const first = await call<{ id: string }>("memory.create", {
    content: "v1",
    tree: "share/conf",
    name: "doc",
  });

  // default → CONFLICT
  await expectAppError(
    call("memory.create", { content: "v2", tree: "share/conf", name: "doc" }),
    "CONFLICT",
  );

  // ignore → returns the existing memory (idempotent), unchanged
  const ignored = await call<{ id: string; content: string }>("memory.create", {
    content: "v2",
    tree: "share/conf",
    name: "doc",
    onConflict: "ignore",
  });
  expect(ignored.id).toBe(first.id);
  expect(ignored.content).toBe("v1");

  // replace → overwrites in place, same id
  const replaced = await call<{ id: string; content: string }>(
    "memory.create",
    { content: "v2", tree: "share/conf", name: "doc", onConflict: "replace" },
  );
  expect(replaced.id).toBe(first.id);
  expect(replaced.content).toBe("v2");
});

test("update can rename and clear a name", async () => {
  const created = await call<{ id: string; versionHash: string }>(
    "memory.create",
    {
      content: "body",
      tree: "share/ren",
      name: "old",
    },
  );
  const renamed = await call<{ name: string | null; versionHash: string }>(
    "memory.update",
    {
      id: created.id,
      versionHash: created.versionHash,
      name: "new",
    },
  );
  expect(renamed.name).toBe("new");
  const cleared = await call<{ name: string | null }>("memory.update", {
    id: created.id,
    versionHash: renamed.versionHash,
    name: null,
  });
  expect(cleared.name).toBeNull();
});

test("update adds a name to a previously-unnamed memory", async () => {
  const created = await call<{
    id: string;
    name: string | null;
    versionHash: string;
  }>("memory.create", { content: "body", tree: "share/addname" });
  expect(created.name).toBeNull();
  const named = await call<{ name: string | null }>("memory.update", {
    id: created.id,
    versionHash: created.versionHash,
    name: "added",
  });
  expect(named.name).toBe("added");
  // The new name is now resolvable as a path.
  const byPath = await call<{ id: string }>("memory.getByPath", {
    path: "share/addname/added",
  });
  expect(byPath.id).toBe(created.id);
});

test("update patches fields", async () => {
  const created = await call<{
    id: string;
    version: number;
    versionHash: string;
  }>("memory.create", {
    content: "before",
    tree: "share.a",
  });
  expect(created.version).toBe(1);
  expect(created.versionHash).toMatch(/^[0-9a-f]{32}$/);

  const updated = await call<{
    content: string;
    tree: string;
    version: number;
    versionHash: string;
  }>("memory.update", {
    id: created.id,
    versionHash: created.versionHash,
    content: "after",
    tree: "share.a.b",
  });
  expect(updated.content).toBe("after");
  expect(updated.tree).toBe("/share/a/b");
  expect(updated.version).toBe(2);
  expect(updated.versionHash).not.toBe(created.versionHash);

  await expectAppError(
    call("memory.update", {
      id: created.id,
      versionHash: created.versionHash,
      content: "stale",
    }),
    "CONFLICT",
  );
});

test("delete removes; get then NOT_FOUND", async () => {
  const created = await call<{ id: string }>("memory.create", {
    content: "doomed",
    tree: "share",
  });
  const res = await call<{ deleted: boolean }>("memory.delete", {
    id: created.id,
  });
  expect(res.deleted).toBe(true);
  await expectAppError(call("memory.get", { id: created.id }), "NOT_FOUND");
});

test("get / delete unknown id → NOT_FOUND", async () => {
  const ghost = crypto.randomUUID();
  await expectAppError(call("memory.get", { id: ghost }), "NOT_FOUND");
  await expectAppError(call("memory.delete", { id: ghost }), "NOT_FOUND");
});

test("batchCreate inserts all and is retrievable", async () => {
  const res = await call<{ results: { id: string; status: string }[] }>(
    "memory.batchCreate",
    {
      memories: [
        { content: "one", tree: "share.batch" },
        { content: "two", tree: "share.batch" },
        { content: "three", tree: "share.batch.sub" },
      ],
    },
  );
  expect(res.results).toHaveLength(3);
  expect(res.results.every((r) => r.status === "inserted")).toBe(true);
  const count = await call<{ count: number }>("memory.countTree", {
    tree: "share.batch",
  });
  expect(count.count).toBe(3);

  const capped = await call<{ count: number }>("memory.countTree", {
    tree: "share.batch",
    maxCount: 2,
  });
  expect(capped.count).toBe(2);
});

test("countTree accepts lquery and ltxtquery tree filters", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "count direct child", tree: "share.countfilter.a" },
      { content: "count deep descendant", tree: "share.countfilter.a.deep" },
      { content: "count both labels", tree: "share.count_alpha.count_beta" },
      { content: "count elsewhere", tree: "share.countfilter_other" },
    ],
  });

  const lquery = await call<{ count: number }>("memory.countTree", {
    tree: "share.countfilter.*",
  });
  expect(lquery.count).toBe(2);

  const ltxtquery = await call<{ count: number }>("memory.countTree", {
    tree: "count_alpha & count_beta",
  });
  expect(ltxtquery.count).toBe(1);
});

test("create with a duplicate explicit id → CONFLICT", async () => {
  const id = "01941000-0000-7000-8000-00000000c0f1";
  await call("memory.create", { id, content: "first", tree: "share.dup" });
  await expectAppError(
    call("memory.create", { id, content: "second", tree: "share.dup" }),
    "CONFLICT",
  );
});

test("batchCreate with a bare duplicate id raises CONFLICT", async () => {
  const id = "01941000-0000-7000-8000-00000000c0f2";
  await call("memory.batchCreate", {
    memories: [{ id, content: "original", tree: "share.skip" }],
  });
  // Default onConflict ('error') → the duplicate id is a hard conflict that
  // aborts the batch (importers pass onConflict 'replace' to stay idempotent).
  await expectAppError(
    call("memory.batchCreate", {
      memories: [{ id, content: "replacement", tree: "share.skip" }],
    }),
    "CONFLICT",
  );
  const got = await call<{ content: string }>("memory.get", { id });
  expect(got.content).toBe("original");
});

test("batchCreate onConflict 'replace' splits insert/update/skip", async () => {
  const stale = "01941000-0000-7000-8000-00000000c0f3";
  const fresh = "01941000-0000-7000-8000-00000000c0f4";
  const brandNew = "01941000-0000-7000-8000-00000000c0f5";
  await call("memory.batchCreate", {
    memories: [
      { id: stale, content: "old render", tree: "share.up", meta: { v: "1" } },
      { id: fresh, content: "current", tree: "share.up", meta: { v: "2" } },
    ],
  });

  const res = await call<{ results: { id: string; status: string }[] }>(
    "memory.batchCreate",
    {
      memories: [
        // changed content → replaced
        {
          id: stale,
          content: "new render",
          tree: "share.up",
          meta: { v: "2" },
        },
        // identical content+meta → content-aware replace no-op (skipped)
        { id: fresh, content: "current", tree: "share.up", meta: { v: "2" } },
        { id: brandNew, content: "added", tree: "share.up", meta: { v: "2" } },
      ],
      onConflict: "replace",
    },
  );
  // One row per input, in input order: replaced / skipped / inserted.
  expect(res.results).toEqual([
    { id: stale, status: "updated" },
    { id: fresh, status: "skipped" },
    { id: brandNew, status: "inserted" },
  ]);

  const updated = await call<{ content: string }>("memory.get", { id: stale });
  expect(updated.content).toBe("new render");
  const skipped = await call<{ content: string }>("memory.get", { id: fresh });
  expect(skipped.content).toBe("current");
});

test("tree returns descendant node counts under a path", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "x", tree: "share.root.a" },
      { content: "y", tree: "share.root.a.deep" },
      { content: "z", tree: "share.root.b" },
    ],
  });
  const res = await call<{ nodes: { path: string; count: number }[] }>(
    "memory.tree",
    { tree: "share.root" },
  );
  const byPath = Object.fromEntries(res.nodes.map((n) => [n.path, n.count]));
  expect(byPath["/share/root/a"]).toBe(2);
  expect(byPath["/share/root/a/deep"]).toBe(1);
  expect(byPath["/share/root/b"]).toBe(1);
  // the base path itself is excluded
  expect(byPath["/share/root"]).toBeUndefined();
});

test("tree respects levels depth limit", async () => {
  await call("memory.batchCreate", {
    memories: [{ content: "deep", tree: "share.t.a.b.c" }],
  });
  const res = await call<{ nodes: { path: string }[] }>("memory.tree", {
    tree: "share.t",
    levels: 1,
  });
  const paths = res.nodes.map((n) => n.path);
  expect(paths).toContain("/share/t/a");
  expect(paths).not.toContain("/share/t/a/b");
});

test("move relocates a subtree (dryRun counts without moving)", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "m1", tree: "share.src.x" },
      { content: "m2", tree: "share.src.y" },
    ],
  });
  const dry = await call<{ count: number }>("memory.move", {
    source: "share.src",
    destination: "share.dst",
    dryRun: true,
  });
  expect(dry.count).toBe(2);
  // still under share.src
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.src" }))
      .count,
  ).toBe(2);

  const moved = await call<{ count: number }>("memory.move", {
    source: "share.src",
    destination: "share.dst",
  });
  expect(moved.count).toBe(2);
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.src" }))
      .count,
  ).toBe(0);
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.dst" }))
      .count,
  ).toBe(2);
});

test("copy duplicates a subtree (dryRun counts without copying)", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "c1", tree: "share.copy_src.x" },
      { content: "c2", tree: "share.copy_src.y" },
    ],
  });

  const dry = await call<{ count: number }>("memory.copy", {
    source: "share.copy_src",
    destination: "share.copy_dst",
    dryRun: true,
  });
  expect(dry.count).toBe(2);
  expect(
    (
      await call<{ count: number }>("memory.countTree", {
        tree: "share.copy_src",
      })
    ).count,
  ).toBe(2);
  expect(
    (
      await call<{ count: number }>("memory.countTree", {
        tree: "share.copy_dst",
      })
    ).count,
  ).toBe(0);

  const copied = await call<{ count: number }>("memory.copy", {
    source: "share.copy_src",
    destination: "share.copy_dst",
  });
  expect(copied.count).toBe(2);
  expect(
    (
      await call<{ count: number }>("memory.countTree", {
        tree: "share.copy_src",
      })
    ).count,
  ).toBe(2);
  expect(
    (
      await call<{ count: number }>("memory.countTree", {
        tree: "share.copy_dst",
      })
    ).count,
  ).toBe(2);
});

test("deleteTree removes a subtree (dryRun counts without deleting)", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "d1", tree: "share.gone.a" },
      { content: "d2", tree: "share.gone.b" },
    ],
  });
  const dry = await call<{ count: number }>("memory.deleteTree", {
    tree: "share.gone",
    dryRun: true,
  });
  expect(dry.count).toBe(2);
  const del = await call<{ count: number }>("memory.deleteTree", {
    tree: "share.gone",
  });
  expect(del.count).toBe(2);
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.gone" }))
      .count,
  ).toBe(0);
});

test("search: fulltext (bm25) finds matching content", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "the quick brown fox", tree: "share.s" },
      { content: "lazy dogs sleep", tree: "share.s" },
    ],
  });
  const res = await call<{ results: { content: string }[]; total: number }>(
    "memory.search",
    { fulltext: "fox" },
  );
  expect(res.total).toBeGreaterThanOrEqual(1);
  expect(res.results.some((r) => r.content.includes("fox"))).toBe(true);
});

test("search: tree filter only (no ranking) returns matches", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "in scope", tree: "share.scope.a" },
      { content: "out of scope", tree: "share.other" },
    ],
  });
  const res = await call<{ results: { tree: string }[] }>("memory.search", {
    tree: "share.scope",
  });
  expect(res.results.length).toBe(1);
  expect(res.results[0]?.tree).toBe("/share/scope/a");
});

test("search: tree lquery wildcard matches descendants", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "direct child", tree: "share.proj.a" },
      { content: "deep descendant", tree: "share.proj.a.deep" },
      { content: "sibling root", tree: "share.proj" },
      { content: "elsewhere", tree: "share.other" },
    ],
  });
  // `share.proj.*` is lquery (not a literal ltree) — it must bind to the
  // lquery param, not cast to ::ltree (which would throw). lquery `*` matches
  // zero-or-more labels, so it matches share.proj and everything under it, but
  // not share.other.
  const res = await call<{ results: { tree: string }[] }>("memory.search", {
    tree: "share.proj.*",
  });
  const trees = res.results.map((r) => r.tree).sort();
  expect(trees).toEqual(["/share/proj", "/share/proj/a", "/share/proj/a/deep"]);

  // Exact-node lquery: `*{0}` matches zero extra labels, pinning the filter
  // to the node itself — the form `me import docs --prune` enumerates with.
  const exact = await call<{ results: { tree: string }[] }>("memory.search", {
    tree: "share.proj.a/*{0}",
  });
  expect(exact.results.map((r) => r.tree)).toEqual(["/share/proj/a"]);
});

test("deleteOrphansInTree deletes stale slots; kept/foreign/unnamed survive; dryRun previews", async () => {
  await call("memory.batchCreate", {
    memories: [
      {
        content: "kept",
        tree: "share.p.docs",
        name: "kept.md",
        meta: { source: "docs" },
      },
      {
        content: "stale",
        tree: "share.p.docs.old",
        name: "stale.md",
        meta: { source: "docs" },
      },
      {
        content: "foreign",
        tree: "share.p.docs",
        name: "manual.md",
        meta: { source: "human" },
      },
      { content: "unnamed", tree: "share.p.docs", meta: { source: "docs" } },
    ],
  });

  const params = {
    root: "share.p.docs",
    metaContains: { source: "docs" },
    keep: [{ tree: "share.p.docs", name: "kept.md" }],
  };

  // Dry run: exact would-delete list, nothing deleted.
  const dry = await call<{ count: number; paths: string[] }>(
    "memory.deleteOrphansInTree",
    { ...params, dryRun: true },
  );
  expect(dry.count).toBe(1);
  expect(dry.paths).toEqual(["/share/p/docs/old/stale.md"]);
  const before = await call<{ count: number }>("memory.countTree", {
    tree: "share.p.docs",
  });
  expect(before.count).toBe(4);

  // Real run: exactly the stale slot goes.
  const res = await call<{ count: number; paths: string[] }>(
    "memory.deleteOrphansInTree",
    params,
  );
  expect(res.count).toBe(1);
  expect(res.paths).toEqual(["/share/p/docs/old/stale.md"]);
  const after = await call<{ count: number }>("memory.countTree", {
    tree: "share.p.docs",
  });
  expect(after.count).toBe(3);

  // Idempotent: a second reconcile with the same keep-list is a no-op.
  const again = await call<{ count: number }>(
    "memory.deleteOrphansInTree",
    params,
  );
  expect(again.count).toBe(0);
});

test("deleteOrphansInTree normalizes ~ and / path spellings in root and keep", async () => {
  await call("memory.batchCreate", {
    memories: [
      {
        content: "kept",
        tree: "~/proj/docs",
        name: "a.md",
        meta: { source: "docs" },
      },
      {
        content: "stale",
        tree: "~/proj/docs",
        name: "b.md",
        meta: { source: "docs" },
      },
    ],
  });
  const res = await call<{ count: number; paths: string[] }>(
    "memory.deleteOrphansInTree",
    {
      root: "~/proj/docs",
      metaContains: { source: "docs" },
      keep: [{ tree: "~/proj/docs", name: "a.md" }],
    },
  );
  expect(res.count).toBe(1);
  expect(res.paths).toEqual(["~/proj/docs/b.md"]);
});

test("deleteOrphansInTree renders a root-level row as /name, not //name", async () => {
  // Root-level rows display their tree as "/" — the path join must not
  // double the separator. Needs owner@root (the seeded owner only holds
  // home + share).
  const core = engineCore.coreStore(sql, coreSchema);
  await core.grantTreeAccess(
    space.id,
    principalId,
    engineCore.ROOT_PATH,
    engineCore.ACCESS.owner,
  );
  treeAccess = await core.buildTreeAccess(principalId, space.id);

  await call("memory.create", {
    content: "root doc",
    tree: "/",
    name: "root.md",
    meta: { source: "docs" },
  });
  const res = await call<{ count: number; paths: string[] }>(
    "memory.deleteOrphansInTree",
    { root: "/", metaContains: { source: "docs" }, keep: [], dryRun: true },
  );
  expect(res.count).toBe(1);
  expect(res.paths).toEqual(["/root.md"]);
});

test("deleteOrphansInTree refuses an empty metaContains scope", async () => {
  await expectAppError(
    call("memory.deleteOrphansInTree", {
      root: "share.p.docs",
      metaContains: {},
      keep: [],
    }),
    "VALIDATION_ERROR",
  );
});

test("search: tree ltxtquery (label boolean) matches by label", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "both labels", tree: "share.alpha.beta" },
      { content: "one label", tree: "share.alpha" },
    ],
  });
  // `alpha & beta` is ltxtquery — must bind to the ltxtquery param.
  const res = await call<{ results: { tree: string }[] }>("memory.search", {
    tree: "alpha & beta",
  });
  expect(res.results.map((r) => r.tree)).toEqual(["/share/alpha/beta"]);
});

test("search: grep alone is rejected", async () => {
  await expectAppError(
    call("memory.search", { grep: "anything" }),
    "VALIDATION_ERROR",
  );
});

test("search: semantic without embedding config → EMBEDDING_NOT_CONFIGURED", async () => {
  await expectAppError(
    call("memory.search", { semantic: "meaning" }),
    "EMBEDDING_NOT_CONFIGURED",
  );
});

test("create without write access → FORBIDDEN", async () => {
  // read-only on the root path
  const readOnly: TreeAccess = [
    { tree_path: "", access: engineCore.ACCESS.read },
  ];
  await expectAppError(
    call("memory.create", { content: "nope", tree: "x" }, readOnly),
    "FORBIDDEN",
  );
});

test("create with no tree access → FORBIDDEN", async () => {
  await expectAppError(
    call("memory.create", { content: "nope", tree: "share.nope" }, []),
    "FORBIDDEN",
  );
});

test("memory.embeddingStatus reports the space embedding backlog", async () => {
  type Status = {
    pending: number;
    inFlight: number;
    waiting: number;
    failed: number;
    oldestPendingAt: string | null;
  };

  // Fresh space → empty backlog.
  expect(await call<Status>("memory.embeddingStatus", {})).toEqual({
    pending: 0,
    inFlight: 0,
    waiting: 0,
    failed: 0,
    oldestPendingAt: null,
  });

  // Creating memories enqueues them (embedding is null → enqueue trigger).
  await call("memory.batchCreate", {
    memories: [
      { content: "one", tree: "share.a" },
      { content: "two", tree: "share.b" },
      { content: "three", tree: "share.c" },
    ],
  });

  const seeded = await call<Status>("memory.embeddingStatus", {});
  expect(seeded.pending).toBe(3);
  expect(seeded.waiting).toBe(3);
  expect(seeded.inFlight).toBe(0);
  expect(seeded.failed).toBe(0);
  // oldest_pending_at (a Date from the store) is serialized to an ISO string.
  expect(seeded.oldestPendingAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);

  // A terminal 'failed' row leaves pending and is counted under failed.
  await sql.unsafe(
    `update me_${space.slug}.embedding_queue set outcome = 'failed'
     where id = (select id from me_${space.slug}.embedding_queue order by id limit 1)`,
  );
  const afterFail = await call<Status>("memory.embeddingStatus", {});
  expect(afterFail.pending).toBe(2);
  expect(afterFail.failed).toBe(1);
});
