// Integration test for the memory RPC data-plane handlers (4C-1).
//
// Provisions a space + owner, then drives the memory.* handlers through the
// registry against a real space schema (me_<slug>). Semantic search is not
// exercised (embeddings are generated by the worker — Phase 4D); fulltext
// (bm25) and filter search are.
//   TEST_DATABASE_URL="postgresql://postgres@127.0.0.1:5432/postgres" \
//     bun test --timeout 30000 \
//     packages/server/rpc/memory/memory.integration.test.ts
import { afterAll, beforeAll, beforeEach, expect, test } from "bun:test";
import {
  bootstrapSpaceDatabase,
  migrateAuth,
  migrateCore,
} from "@memory.build/database";
import type { TreeAccess } from "@memory.build/engine/core";
import * as engineCore from "@memory.build/engine/core";
import type { SpaceStore } from "@memory.build/engine/space";
import * as engineSpace from "@memory.build/engine/space";
import { type AppErrorCode, isAppError } from "@memory.build/protocol/errors";
import postgres, { type Sql } from "postgres";
import { provisionUser } from "../../provision";
import type { HandlerContext } from "../types";
import { memoryDataMethods } from "./memory";

const URL =
  process.env.TEST_DATABASE_URL ??
  "postgresql://postgres@127.0.0.1:5432/postgres";

const rand = () => {
  const a = "abcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = crypto.getRandomValues(new Uint8Array(8));
  let s = "";
  for (const b of bytes) s += a[b % 36];
  return s;
};

let sql: Sql;
let authSchema: string;
let coreSchema: string;
const createdSpaceSchemas: string[] = [];

// Per-test space context.
let store: SpaceStore;
let treeAccess: TreeAccess;
let space: { id: string; slug: string };
let principalId: string;

function call<T = unknown>(
  method: string,
  params: unknown,
  ta: TreeAccess = treeAccess,
): Promise<T> {
  const registered = memoryDataMethods.get(method);
  if (!registered) throw new Error(`no handler for ${method}`);
  const context = {
    request: new Request("http://localhost/api/v1/memory/rpc"),
    store,
    core: engineCore.coreStore(sql, coreSchema),
    space,
    principalId,
    apiKeyId: null,
    treeAccess: ta,
  } as unknown as HandlerContext;
  return registered.handler(params, context) as Promise<T>;
}

/** Assert a handler call rejects with a specific AppError code. */
async function expectAppError(p: Promise<unknown>, code: AppErrorCode) {
  try {
    await p;
    throw new Error(`expected AppError(${code}), but it resolved`);
  } catch (e) {
    if (!isAppError(e)) throw e;
    expect(e.code).toBe(code);
  }
}

beforeAll(async () => {
  sql = postgres(URL, { onnotice: () => {} });
  authSchema = `auth_test_${rand()}`;
  coreSchema = `core_test_${rand()}`;
  await bootstrapSpaceDatabase(sql);
  await migrateAuth(sql, { schema: authSchema });
  await migrateCore(sql, { schema: coreSchema });
});

afterAll(async () => {
  for (const s of createdSpaceSchemas) {
    await sql.unsafe(`drop schema if exists ${s} cascade`);
  }
  await sql.unsafe(`drop schema if exists ${authSchema} cascade`);
  await sql.unsafe(`drop schema if exists ${coreSchema} cascade`);
  await sql.end();
});

// Fresh space per test so trees don't bleed across cases.
beforeEach(async () => {
  const core = engineCore.coreStore(sql, coreSchema);
  const r = await provisionUser(
    sql,
    { auth: authSchema, core: coreSchema },
    {
      email: `mem_${crypto.randomUUID().slice(0, 8)}@example.com`,
      name: "Owner",
      provider: "github",
      accountId: crypto.randomUUID(),
    },
  );
  createdSpaceSchemas.push(`me_${r.spaceSlug}`);
  store = engineSpace.spaceStore(sql, `me_${r.spaceSlug}`);
  // The default creator owns its home + the shared root (`share`), not the whole
  // tree — so these tests write under `share.*`. (The normalization test, which
  // needs arbitrary paths, elevates itself to owner@root.)
  treeAccess = await core.buildTreeAccess(r.userId, r.spaceId);
  space = { id: r.spaceId, slug: r.spaceSlug };
  principalId = r.userId;
});

test("~ home + lenient separators normalize on input, reverse-map on output", async () => {
  // This test writes to arbitrary (non-home, non-share) paths to exercise path
  // normalization, so elevate the owner to owner@root for it.
  const core = engineCore.coreStore(sql, coreSchema);
  await core.grantTreeAccess(
    space.id,
    principalId,
    engineCore.ROOT_PATH,
    engineCore.ACCESS.owner,
  );
  treeAccess = await core.buildTreeAccess(principalId, space.id);

  const home = `home.${principalId.replace(/-/g, "")}`;

  // `~/notes` (slash accepted on input) stores under the caller's home and
  // reads back in canonical dot form as `~.notes`.
  const a = await call<{ id: string; tree: string }>("memory.create", {
    content: "home note",
    tree: "~/notes",
  });
  expect(a.tree).toBe("~.notes");
  expect((await call<{ tree: string }>("memory.get", { id: a.id })).tree).toBe(
    "~.notes",
  );

  // The raw stored ltree is home.<id>.notes — proves real expansion, not just display.
  const [row] = await sql.unsafe(
    `select tree::text as tree from me_${space.slug}.memory where id = $1`,
    [a.id],
  );
  expect(row?.tree).toBe(`${home}.notes`);

  // Slash input normalizes to dot ltree; non-home paths display canonically.
  const b = await call<{ tree: string }>("memory.create", {
    content: "slashy",
    tree: "/work/projects/",
  });
  expect(b.tree).toBe("work.projects");

  // memory.tree with a `~` base finds the home node, reverse-mapped to `~.notes`.
  const tree = await call<{ nodes: { path: string; count: number }[] }>(
    "memory.tree",
    { tree: "~" },
  );
  expect(tree.nodes.some((n) => n.path === "~.notes")).toBe(true);

  // An illegal label is a validation error.
  await expectAppError(
    call("memory.create", { content: "x", tree: "bad label" }),
    "VALIDATION_ERROR",
  );
});

test("create → get round-trips content/tree/meta and createdBy is null", async () => {
  const created = await call<{ id: string; createdBy: string | null }>(
    "memory.create",
    { content: "hello world", tree: "share.notes.work", meta: { tag: "a" } },
  );
  expect(created.createdBy).toBeNull();

  const got = await call<{
    id: string;
    content: string;
    tree: string;
    meta: Record<string, unknown>;
    hasEmbedding: boolean;
  }>("memory.get", { id: created.id });
  expect(got.content).toBe("hello world");
  expect(got.tree).toBe("share.notes.work");
  expect(got.meta).toEqual({ tag: "a" });
  expect(got.hasEmbedding).toBe(false);
});

test("create with temporal round-trips as {start,end}", async () => {
  const created = await call<{ id: string }>("memory.create", {
    content: "temporal one",
    tree: "share",
    temporal: { start: "2024-01-01T00:00:00Z", end: "2024-01-02T00:00:00Z" },
  });
  const got = await call<{ temporal: { start: string; end: string } | null }>(
    "memory.get",
    { id: created.id },
  );
  expect(got.temporal).toEqual({
    start: "2024-01-01T00:00:00.000Z",
    end: "2024-01-02T00:00:00.000Z",
  });
});

test("update patches fields", async () => {
  const created = await call<{ id: string }>("memory.create", {
    content: "before",
    tree: "share.a",
  });
  const updated = await call<{ content: string; tree: string }>(
    "memory.update",
    { id: created.id, content: "after", tree: "share.a.b" },
  );
  expect(updated.content).toBe("after");
  expect(updated.tree).toBe("share.a.b");
});

test("delete removes; get then NOT_FOUND", async () => {
  const created = await call<{ id: string }>("memory.create", {
    content: "doomed",
    tree: "share",
  });
  const res = await call<{ deleted: boolean }>("memory.delete", {
    id: created.id,
  });
  expect(res.deleted).toBe(true);
  await expectAppError(call("memory.get", { id: created.id }), "NOT_FOUND");
});

test("get / delete unknown id → NOT_FOUND", async () => {
  const ghost = crypto.randomUUID();
  await expectAppError(call("memory.get", { id: ghost }), "NOT_FOUND");
  await expectAppError(call("memory.delete", { id: ghost }), "NOT_FOUND");
});

test("batchCreate inserts all and is retrievable", async () => {
  const res = await call<{ ids: string[] }>("memory.batchCreate", {
    memories: [
      { content: "one", tree: "share.batch" },
      { content: "two", tree: "share.batch" },
      { content: "three", tree: "share.batch.sub" },
    ],
  });
  expect(res.ids).toHaveLength(3);
  const count = await call<{ count: number }>("memory.countTree", {
    tree: "share.batch",
  });
  expect(count.count).toBe(3);
});

test("tree returns descendant node counts under a path", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "x", tree: "share.root.a" },
      { content: "y", tree: "share.root.a.deep" },
      { content: "z", tree: "share.root.b" },
    ],
  });
  const res = await call<{ nodes: { path: string; count: number }[] }>(
    "memory.tree",
    { tree: "share.root" },
  );
  const byPath = Object.fromEntries(res.nodes.map((n) => [n.path, n.count]));
  expect(byPath["share.root.a"]).toBe(2);
  expect(byPath["share.root.a.deep"]).toBe(1);
  expect(byPath["share.root.b"]).toBe(1);
  // the base path itself is excluded
  expect(byPath["share.root"]).toBeUndefined();
});

test("tree respects levels depth limit", async () => {
  await call("memory.batchCreate", {
    memories: [{ content: "deep", tree: "share.t.a.b.c" }],
  });
  const res = await call<{ nodes: { path: string }[] }>("memory.tree", {
    tree: "share.t",
    levels: 1,
  });
  const paths = res.nodes.map((n) => n.path);
  expect(paths).toContain("share.t.a");
  expect(paths).not.toContain("share.t.a.b");
});

test("move relocates a subtree (dryRun counts without moving)", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "m1", tree: "share.src.x" },
      { content: "m2", tree: "share.src.y" },
    ],
  });
  const dry = await call<{ count: number }>("memory.move", {
    source: "share.src",
    destination: "share.dst",
    dryRun: true,
  });
  expect(dry.count).toBe(2);
  // still under share.src
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.src" }))
      .count,
  ).toBe(2);

  const moved = await call<{ count: number }>("memory.move", {
    source: "share.src",
    destination: "share.dst",
  });
  expect(moved.count).toBe(2);
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.src" }))
      .count,
  ).toBe(0);
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.dst" }))
      .count,
  ).toBe(2);
});

test("deleteTree removes a subtree (dryRun counts without deleting)", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "d1", tree: "share.gone.a" },
      { content: "d2", tree: "share.gone.b" },
    ],
  });
  const dry = await call<{ count: number }>("memory.deleteTree", {
    tree: "share.gone",
    dryRun: true,
  });
  expect(dry.count).toBe(2);
  const del = await call<{ count: number }>("memory.deleteTree", {
    tree: "share.gone",
  });
  expect(del.count).toBe(2);
  expect(
    (await call<{ count: number }>("memory.countTree", { tree: "share.gone" }))
      .count,
  ).toBe(0);
});

test("search: fulltext (bm25) finds matching content", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "the quick brown fox", tree: "share.s" },
      { content: "lazy dogs sleep", tree: "share.s" },
    ],
  });
  const res = await call<{ results: { content: string }[]; total: number }>(
    "memory.search",
    { fulltext: "fox" },
  );
  expect(res.total).toBeGreaterThanOrEqual(1);
  expect(res.results.some((r) => r.content.includes("fox"))).toBe(true);
});

test("search: tree filter only (no ranking) returns matches", async () => {
  await call("memory.batchCreate", {
    memories: [
      { content: "in scope", tree: "share.scope.a" },
      { content: "out of scope", tree: "share.other" },
    ],
  });
  const res = await call<{ results: { tree: string }[] }>("memory.search", {
    tree: "share.scope",
  });
  expect(res.results.length).toBe(1);
  expect(res.results[0]?.tree).toBe("share.scope.a");
});

test("search: grep alone is rejected", async () => {
  await expectAppError(
    call("memory.search", { grep: "anything" }),
    "VALIDATION_ERROR",
  );
});

test("search: semantic without embedding config → EMBEDDING_NOT_CONFIGURED", async () => {
  await expectAppError(
    call("memory.search", { semantic: "meaning" }),
    "EMBEDDING_NOT_CONFIGURED",
  );
});

test("create without write access → FORBIDDEN", async () => {
  // read-only on the root path
  const readOnly: TreeAccess = [
    { tree_path: "", access: engineCore.ACCESS.read },
  ];
  await expectAppError(
    call("memory.create", { content: "nope", tree: "x" }, readOnly),
    "FORBIDDEN",
  );
});
